### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by igorkamyshev** [effector/farfetched#10]
# Releases

## v.0.2 [Laem Promthep](https://github.com/igorkamyshev/farfetched/milestone/2)

- [ ] `@farfetched/core` 
	- [ ] `createJsonMutation` 
	- [ ] `createMutation` 
	- [ ] handle `stale` after mutation
	- [ ] postpone mutation (analogue of `connectQuery`)
	- [ ] optimistic update operator
	- [ ] automagic refetch
	- [ ] Retry API
	- [ ] initial for `createHeadlessQuery`
- [ ] `@farfetched/react` 
	- [ ] `useMutation`

## v.0.3 cache

Declarative cache

- [ ] Other query-libs comparison
- [ ] `@farfetched/cache` 
	- [ ] `cacheQuery` 
	- [ ] `memoryCache`
	- [ ] `persistentCache` 
- [ ] dev.to announce
- [ ] testing guide
- [ ] additional showcase for caching

## v.0.4 GraphQL

- [ ] Update comparison
- [ ] `@farfetched/graphql` 
	- [ ] `createGraphQLQuery` 
	- [ ] `createGraphQLMutation`
	- [ ] optional auto-batching
	- [ ] import, parsing, and usage of schema
	- [ ] choose library to handle GraphQL-stuff
	- [ ] automatic optimistic update for Query based on Mutation and schema
- [ ] dev.to announce
- [ ] additional showcase for GraphQL

## v.0.5 DevTools 

- [ ] Project identity
- [ ] Design of DevTools
- [ ] Choose UI-engine (forest? solid?)
- [ ] #42 
- [ ] dev.to announce
- [ ] talk

## v.0.6 lists

Paginations and infinite scroll

## v.0.7 solid

- [x] `@farfetched/solid`

## v.0.8 triggers

Mark data as stale and re-fetch on some declarative triggers.

- [ ] Trigger API
- [ ] `@farfetched/web-api`
	- [ ] internet connectivity after lost
	- [ ] tab focus
- [ ] timers
- [ ] explicit triggers
- [ ] migrate Mutation API to Triggers API, migrate `connectQuery` to Triggers API

## v.0.9 polling

Get updates from the server

- [ ] WebSocket
- [ ] Server Sent Events
- [ ] HTTP Polling

## v.0.10 REST

- [ ] `createREST` — return set of queries and mutations for typical REST API

## v.0.11 Suspense

- [ ] `@farfetched/react` 
	- [ ] Suspense
- [ ] dev.to announce
- [ ] Showcase with SSR and Suspense

## v.1

Stable release 🎉
